const STORAGE_KEY='clientflow-demo-v1';
const fallback={settings:{business:'Studio Aurora',whatsapp:'5521999999999',start:'09:00',end:'19:00'},services:[{id:'srv1',name:'Corte premium',duration:50,price:65,description:''},{id:'srv2',name:'Barba + acabamento',duration:35,price:45,description:''},{id:'srv3',name:'Pacote completo',duration:80,price:105,description:''},{id:'srv4',name:'Consultoria de imagem',duration:60,price:120,description:''}],clients:[],appointments:[],quotes:[],revenue:[5800,6400,6100,7200,7900,8900]};
let state;try{state=JSON.parse(localStorage.getItem(STORAGE_KEY))||fallback}catch{state=fallback}
const $=s=>document.querySelector(s);const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const clean=v=>String(v||'').replace(/\D/g,'');const uid=p=>`${p}${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`;
$('#public-business').textContent=state.settings?.business||'Seu negócio';
$('#public-service').innerHTML='<option value="">Escolha um serviço</option>'+state.services.map(s=>`<option value="${s.id}">${s.name} — ${money(s.price)}</option>`).join('');
const now=new Date(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);$('#public-date').min=now.toISOString().slice(0,10);$('#public-date').value=tomorrow.toISOString().slice(0,10);
function renderTimes(){const start=(state.settings?.start||'09:00').split(':').map(Number),end=(state.settings?.end||'19:00').split(':').map(Number),slots=[];for(let m=start[0]*60+start[1];m<=end[0]*60+end[1]-30;m+=30){slots.push(`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`)}const busy=new Set((state.appointments||[]).filter(a=>a.date===$('#public-date').value&&a.status!=='cancelled').map(a=>a.time));$('#public-time').innerHTML=slots.filter(t=>!busy.has(t)).map(t=>`<option>${t}</option>`).join('')||'<option value="">Sem horários disponíveis</option>'}
renderTimes();$('#public-date').addEventListener('change',renderTimes);
$('#public-booking-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#public-name').value.trim(),phone=clean($('#public-phone').value),serviceId=$('#public-service').value,date=$('#public-date').value,time=$('#public-time').value;if(!name||!phone||!serviceId||!date||!time)return;let client=(state.clients||[]).find(c=>clean(c.phone)===phone);if(!client){client={id:uid('cli'),name,phone,email:'',notes:'Agendamento pela página pública.',visits:0,lastVisit:''};state.clients=state.clients||[];state.clients.push(client)}state.appointments=state.appointments||[];state.appointments.push({id:uid('apt'),clientId:client.id,serviceId,date,time,status:'pending'});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#public-booking-form').hidden=true;$('#public-success').hidden=false});